### ISSUE TITLE
Total length of `Dataloader` across ranks is zero. Please make sure that it returns at least 1 batch.

### ISSUE THREAD

**Issue by lyndonlauder** [KinWaiCheuk/demucs_lightning#10]
Hello, i am getting this error when i try to train. Please do you have any advice on how to fix this? I have three folders inside my training dir, train, valid and test, but i still get this error.

Validation sanity check: 0it [00:00, ?it/s]Error executing job with overrides: ['trainer.precision=16', 'batch_size=1', 'data_augmentation=False', 'model=HDemucs']
Traceback (most recent call last):
  File "train.py", line 130, in main
    trainer.fit(model, train_loader,valid_loader)
  File "/usr/local/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 741, in fit
    self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path
  File "/usr/local/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 685, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 777, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/usr/local/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1199, in _run
    self._dispatch()
  File "/usr/local/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1279, in _dispatch
    self.training_type_plugin.start_training(self)
  File "/usr/local/lib/python3.7/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 202, in start_training
    self._results = trainer.run_stage()
  File "/usr/local/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1289, in run_stage
    return self._run_train()
  File "/usr/local/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1311, in _run_train
    self._run_sanity_check(self.lightning_module)
  File "/usr/local/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1371, in _run_sanity_check
    self._evaluation_loop._reload_evaluation_dataloaders()
  File "/usr/local/lib/python3.7/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 170, in _reload_evaluation_dataloaders
    self.trainer.reset_val_dataloader()
  File "/usr/local/lib/python3.7/site-packages/pytorch_lightning/trainer/data_loading.py", line 548, in reset_val_dataloader
    RunningStage.VALIDATING, model=pl_module
  File "/usr/local/lib/python3.7/site-packages/pytorch_lightning/trainer/data_loading.py", line 504, in _reset_eval_dataloader
    if has_len_all_ranks(dataloader, self.training_type_plugin, module)
  File "/usr/local/lib/python3.7/site-packages/pytorch_lightning/utilities/data.py", line 119, in has_len_all_ranks
    "Total length of `Dataloader` across ranks is zero. Please make sure that it returns at least 1 batch."
pytorch_lightning.utilities.exceptions.MisconfigurationException: Total length of `Dataloader` across ranks is zero. Please make sure that it returns at least 1 batch.

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by KinWaiCheuk** [comment]
It seems to me that your code is unable to locate the dataset. Can you please double check if the attribute `data_root` inside `conf/config.yaml` is pointing to the correct path?

**Comment by KinWaiCheuk** [comment]
Are you trying to use your own dataset? Or using your own validation split?
MUSDB18 dataset does not have a validation set. So our default dataloader loads the train set, and then split it into `train_set` and `valid_set`. It does not look for the specific `validation` folder to load the `valid_set`.

We follow the same validation split as the original [demucs ](https://github.com/facebookresearch/demucs) code. So you might need to write your own `Dataset` class to load your custom split.
